//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenWebPayroll.UI.main.views {
    
    
    public partial class ListingDataFormControlCollectionManager {
        
        /// <summary>
        /// BranchesFormInstance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RavenWebPayroll.UI.main.views.configuration.BranchesForm BranchesFormInstance;
    }
}
